# code: language=ansible
---
- name: "Generate a root CA CRL (in case the root CA key is encrypted)"
  delegate_to: "{{ groups.root_ca[0] }}"
  become: false
  ansible.builtin.command: openssl ca -gencrl -config /ca/openssl.cnf -out /ca/{{ sub_ca_root_ca_name }}.crl -passin pass:{{ root_private_key_pass.user_input }}
  when: root_private_key_pass.user_input is defined

- name: "Generate a root CA CRL (if the root CA key is unencrypted)"
  delegate_to: "{{ groups.root_ca[0] }}"
  become: false
  ansible.builtin.command: openssl ca -gencrl -config /ca/openssl.cnf -out /ca/{{ sub_ca_root_ca_name }}.crl
  when: root_private_key_pass.user_input is not defined

- name: "Fix permissions on the root CA CRL"
  delegate_to: "{{ groups.root_ca[0] }}"
  become: false
  ansible.builtin.file:
    path: "/ca/{{ sub_ca_root_ca_name }}.crl"
    state: file
    mode: "0640"
    owner: "{{ sub_ca_root_ca_user }}"
    group: "{{ sub_ca_root_ca_group }}"
