# code: language=ansible
---
- name: "Final message"
  ansible.builtin.debug:
    msg: |
      You have revoked the following certificates:
      "{{ revoke_certificate_serial }}"
      "{{ serial_numbers['results'] | map(attribute='stdout_lines') | flatten }}"
  when:
    - revoke_certificate_serial is defined
    - serial_numbers is defined

- name: "Final message"
  ansible.builtin.debug:
    msg: |
      You have revoked the following certificates:
      "{{ revoke_certificate_serial }}"
  when:
    - revoke_certificate_serial is defined
    - serial_numbers is not defined

- name: "Final message"
  ansible.builtin.debug:
    msg: |
      You have revoked the following certificates:
      "{{ serial_numbers['results'] | map(attribute='stdout_lines') | flatten }}"
  when:
    - revoke_certificate_serial is not defined
    - serial_numbers is defined
