# code: language=ansible
---
- name: "Generate a CA CRL (in case the CA key is encrypted)"
  become: false
  ansible.builtin.command: openssl ca -gencrl -config /ca/openssl.cnf -out /ca/{{ revoke_certificate_ca_name }}.crl \
                           -passin pass:{{ ca_private_key_pass.user_input }}
  when: ca_private_key_pass.user_input is defined

- name: "Generate a CA CRL (if the CA key is unencrypted)"
  become: false
  ansible.builtin.command: openssl ca -gencrl -config /ca/openssl.cnf -out /ca/{{ revoke_certificate_ca_name }}.crl
  when: ca_private_key_pass.user_input is not defined

- name: "Fix permissions on the sub CA CRL"
  become: false
  ansible.builtin.file:
    path: "/ca/{{ revoke_certificate_ca_name }}.crl"
    state: file
    mode: "0640"
    owner: "{{ revoke_certificate_ca_user }}"
    group: "{{ revoke_certificate_ca_group }}"
