# code: language=ansible
---
- name: "Generate CSRs and keys based on the openssl configs"
  become: false
  delegate_to: localhost
  ansible.builtin.command: openssl req -config /home/{{ localhost_user.stdout }}/home_lab_ca_local/configs/{{ item.cn }}.cnf \
           -new -out /home/{{ localhost_user.stdout }}/home_lab_ca_local/csrs/{{ item.cn }}.csr \
           -newkey rsa:{{ sign_certificate_key_length }} -nodes -keyout /home/{{ localhost_user.stdout }}/home_lab_ca_local/private/{{ item.cn }}.key

- name: "Fix permissions on the CSR"
  become: false
  delegate_to: localhost
  ansible.builtin.file:
    path: "/home/{{ localhost_user.stdout }}/home_lab_ca_local/csrs/{{ item.cn }}.csr"
    state: file
    mode: "0600"
    owner: "{{ localhost_user.stdout }}"

- name: "Fix permissions on the key"
  become: false
  delegate_to: localhost
  ansible.builtin.file:
    path: "/home/{{ localhost_user.stdout }}/home_lab_ca_local/private/{{ item.cn }}.key"
    state: file
    mode: "0600"
    owner: "{{ localhost_user.stdout }}"
