# code: language=ansible
---
- name: "Generate CSRs and keys based on the openssl configs"
  become: false
  delegate_to: localhost
  ansible.builtin.command: openssl req -config /home/{{ sign_certificate_local_user }}/home_lab_ca/configs/{{ item.cn }}.cnf \
           -new -out /home/{{ sign_certificate_local_user }}/home_lab_ca/csrs/{{ item.cn }}.csr \
           -newkey rsa:{{ sign_certificate_key_length }} -nodes -keyout /home/{{ sign_certificate_local_user }}/home_lab_ca/private/{{ item.cn }}.key

- name: "Fix permissions on the CSR"
  become: false
  delegate_to: localhost
  ansible.builtin.file:
    path: "/home/{{ sign_certificate_local_user }}/home_lab_ca/csrs/{{ item.cn }}.csr"
    state: file
    mode: "0600"
    owner: "{{ sign_certificate_local_user }}"

- name: "Fix permissions on the key"
  become: false
  delegate_to: localhost
  ansible.builtin.file:
    path: "/home/{{ sign_certificate_local_user }}/home_lab_ca/private/{{ item.cn }}.key"
    state: file
    mode: "0600"
    owner: "{{ sign_certificate_local_user }}"
