# code: language=ansible
---
- name: "Get localhost current user name"
  become: false
  delegate_to: localhost
  ansible.builtin.command: whoami
  register: localhost_user

- name: "Make directory structure"
  become: false
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ localhost_user.stdout }}"
  loop:
    - "/home/{{ localhost_user.stdout }}/home_lab_ca_local"
    - "/home/{{ localhost_user.stdout }}/home_lab_ca_local/csrs"
    - "/home/{{ localhost_user.stdout }}/home_lab_ca_local/private"
    - "/home/{{ localhost_user.stdout }}/home_lab_ca_local/certs"
    - "/home/{{ localhost_user.stdout }}/home_lab_ca_local/configs"
