# code: language=ansible
---
- name: "Make directory structure"
  become: false
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ sign_certificate_local_user }}"
  loop:
    - "/home/{{ sign_certificate_local_user }}/home_lab_ca"
    - "/home/{{ sign_certificate_local_user }}/home_lab_ca/csrs"
    - "/home/{{ sign_certificate_local_user }}/home_lab_ca/private"
    - "/home/{{ sign_certificate_local_user }}/home_lab_ca/certs"
    - "/home/{{ sign_certificate_local_user }}/home_lab_ca/configs"
